-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_tokendefaults`;
DROP TABLE IF EXISTS `civicrm_tokendefaults_set`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_tokendefaults_set
-- *
-- * Token Defaults Set
-- *
-- *******************************************************/
CREATE TABLE `civicrm_tokendefaults_set` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique TokendefaultsSet ID',
     `title` varchar(255)    ,
     `is_default` tinyint     
,
        PRIMARY KEY (`id`)
 
 
 
)    ;

-- /*******************************************************
-- *
-- * civicrm_tokendefaults
-- *
-- * Token Defaults
-- *
-- *******************************************************/
CREATE TABLE `civicrm_tokendefaults` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique Tokendefaults ID',
     `token` varchar(255)    ,
     `default` varchar(255)    ,
     `is_active` tinyint    ,
     `set_id` int unsigned    COMMENT 'FK to Tokendefaults Set' 
,
        PRIMARY KEY (`id`)
 
 
,          CONSTRAINT FK_civicrm_tokendefaults_set_id FOREIGN KEY (`set_id`) REFERENCES `civicrm_tokendefaults_set`(`id`) ON DELETE CASCADE  
)    ;

 